name: Simple vs Random
seed: 1
players:
  - type: random
    name: Random 1
  - type: random
    name: Random 2
  - type: random
    name: Random 3
  - type: random
    name: Random 4
games: 1
max_points: 13
